// Toolbar icons: 14x14 pixel maps in the game's palette (never scaled).

import type { PixelSprite } from "./art";

const PALETTE: Record<string, string> = {
  K: "#3b2a3a",
  W: "#fff6e6",
  w: "#e8d9bd",
  Y: "#f5c542",
  y: "#c99a3e",
  P: "#e89aa8",
  G: "#9aa0b0",
  g: "#4a3a5a",
  C: "#8fe0e0",
  N: "#a86f43",
  n: "#7a4a2a",
  R: "#d9503f",
  T: "#e8c89a",
  D: "#5b5470",
  S: "#c9c1d4",
  s: "#8a8298",
};

const ICONS: Record<string, string[]> = {
  moonpad: [
    "..KKKKKKKKKK..",
    "..KggggggggK..",
    "..KgCCCCCCgK..",
    "..KgCWWWCCgK..",
    "..KgCCCCCCgK..",
    "..KgCWWWWCgK..",
    "..KgCCCCCCgK..",
    "..KgCWWCCCgK..",
    "..KgCCCCCCgK..",
    "..KgCCCCCCgK..",
    "..KggggggggK..",
    "..KgggWWgggK..",
    "..KggggggggK..",
    "..KKKKKKKKKK..",
  ],
  shop: [
    ".KKKKKKKKKKKK.",
    ".KNNNNNNNNNNK.",
    ".KnnnnnnnnnnK.",
    ".KKKKKKKKKKKK.",
    ".KNNNNKKNNNNK.",
    ".KNNNKYYKNNNK.",
    ".KNNKYWYYKNNK.",
    ".KNNKYYYyKNNK.",
    ".KNNNKYyKNNNK.",
    ".KNNNNKKNNNNK.",
    ".KNNNNNNNNNNK.",
    ".KnnnnnnnnnnK.",
    ".KKKKKKKKKKKK.",
  ],
  quests: [
    ".KKKKKKKKKKK..",
    "KTWWWWWWWWWWK.",
    "KTKKKKKKKKKKK.",
    ".KWWWWWWWWWK..",
    ".KWWWWYWWWWK..",
    ".KWWWYYYWWWK..",
    ".KWYYYYYYYWK..",
    ".KWWYYYYYWWK..",
    ".KWWYYWYYWWK..",
    ".KWWWWWWWWWK..",
    ".KwwwwwwwwwK..",
    ".KKKKKKKKKKKK.",
    "..KWWWWWWWWWTK",
    "...KKKKKKKKKK.",
  ],
  help: [
    "....KKKKKK....",
    "...KWWWWWWK...",
    "..KWWKKKKWWK..",
    "..KWWK..KWWK..",
    "..KKKK..KWWK..",
    ".......KWWK...",
    "......KWWK....",
    "......KWWK....",
    "......KKKK....",
    "..............",
    "......KKKK....",
    "......KWWK....",
    "......KWWK....",
    "......KKKK....",
  ],
  call: [
    ".KKK..........",
    "KWWWK.........",
    "KWWWWK........",
    "KWWWWK........",
    ".KWWK.........",
    ".KWWK.........",
    "..KWWK........",
    "..KWWWK..KKK..",
    "...KWWWKKWWWK.",
    "....KWWWWWWWWK",
    ".....KWWWWWWWK",
    "......KKWWWWK.",
    "........KKKK..",
  ],
  edit: [
    "...........KK.",
    "..........KPPK",
    ".........KGPPK",
    "........KYGGK.",
    ".......KYYyK..",
    "......KYYyK...",
    ".....KYYyK....",
    "....KYYyK.....",
    "...KYYyK......",
    "..KYYyK.......",
    ".KTYyK........",
    ".KTTK.........",
    "KDKK..........",
    ".K............",
  ],
  talk: [
    "..............",
    "..KKKKKKKKKK..",
    ".KWWWWWWWWWWK.",
    "KWWWWWWWWWWWWK",
    "KWWKKWWKKWWKWK",
    "KWWKKWWKKWWKWK",
    "KWWWWWWWWWWWWK",
    ".KWWWWWWWWWWK.",
    "..KKWWKKKKKK..",
    "...KWK........",
    "...KK.........",
  ],
  letter: [
    "..............",
    "..............",
    "KKKKKKKKKKKKKK",
    "KWKWWWWWWWWKWK",
    "KWWKWWWWWWKWWK",
    "KWWWKWWWWKWWWK",
    "KWWWWKRRKWWWWK",
    "KWWWWWKKWWWWWK",
    "KWWWWWWWWWWWWK",
    "KwwwwwwwwwwwwK",
    "KKKKKKKKKKKKKK",
  ],
  build: [
    "..KKKKKKK.....",
    ".KGGGGGGGK....",
    "KGWWGGGGGGK...",
    "KGGGGGGGGGK...",
    ".KKKKNNKKKK...",
    "....KNNK......",
    "....KNNK......",
    "....KNNK......",
    "....KNNK......",
    "....KNNK......",
    "....KnnK......",
    "....KKKK......",
  ],
  grab: [
    "..............",
    ".....KKKK.....",
    "...KKSSSSKK...",
    "..KSSWSSSSSK..",
    ".KSSSSSSsSSSK.",
    ".KSsSSSSSSSSK.",
    ".KSSSSSsSSSsK.",
    ".KsSSSSSSSSSK.",
    "..KssSSSSSsK..",
    "...KKsssssKK..",
    ".....KKKKK....",
  ],
  sweep: [
    "...........KK.",
    "..........KNK.",
    ".........KNK..",
    "........KNK...",
    ".......KNK....",
    "......KNK.....",
    ".....KNK......",
    "...KKYYK......",
    "..KYYYYYK.....",
    ".KYYYYYYK.....",
    "KYYyYyYK......",
    "KYyYyYK.......",
    ".KKKKK........",
  ],
  light: [
    ".....KKKK.....",
    "....KYYYYK....",
    "...KYWWYYyK...",
    "...KYWYYYyK...",
    "...KYYYYYyK...",
    "...KYYYYYyK...",
    "....KYYYyK....",
    ".....KYyK.....",
    ".....KGGK.....",
    ".....KssK.....",
    ".....KGGK.....",
    ".....KKKK.....",
  ],
  idle: [
    "..............",
    "..............",
    "..............",
    "..............",
    "..............",
    "..............",
    ".....KKKK.....",
    ".....KssK.....",
    ".....KssK.....",
    ".....KKKK.....",
  ],
  // Talk-dialog controls: push-to-talk mic (red while listening) and the voice toggle.
  mic: [
    "...KKK...",
    "..KWWWK..",
    "..KWsWK..",
    "..KWWWK..",
    "..KWsWK..",
    "..KWWWK..",
    "K.KKKKK.K",
    "K.......K",
    ".K.....K.",
    "..KKKKK..",
    "....K....",
    "..KKKKK..",
  ],
  mic_on: [
    "...KKK...",
    "..KRRRK..",
    "..KRWRK..",
    "..KRRRK..",
    "..KRWRK..",
    "..KRRRK..",
    "K.KKKKK.K",
    "K.......K",
    ".K.....K.",
    "..KKKKK..",
    "....K....",
    "..KKKKK..",
  ],
  sound_on: [
    "...W......",
    "..WW...W..",
    "WWWW.W..W.",
    "WWWW.W..W.",
    "WWWW.W..W.",
    "..WW...W..",
    "...W......",
  ],
  sound_off: [
    "...W......",
    "..WW.W...W",
    "WWWW..W.W.",
    "WWWW...W..",
    "WWWW..W.W.",
    "..WW.W...W",
    "...W......",
  ],
};

/** Every icon as a one-frame PixelSprite, keyed by name (texture `icon_<name>_0`). */
export const ICON_SPRITES: Record<string, PixelSprite> = Object.fromEntries(
  Object.entries(ICONS).map(([name, rows]) => [name, { palette: PALETTE, frames: [rows] }]),
);

/** The context action button's icon for each verb. */
export const VERB_ICON: Record<string, string> = {
  TALK: "icon_talk_0",
  "READ LETTER": "icon_letter_0",
  BUILD: "icon_build_0",
  POP: "clod_icon",
  GRAB: "icon_grab_0",
  SWEEP: "icon_sweep_0",
  CALL: "icon_call_0",
  "TURN ON": "icon_light_0",
  "TURN OFF": "icon_light_0",
};

/** Tiny 7x7 villager heads, for the minimap and the roster (texture `vicon_<id>_0`). */
export const VILLAGER_ICONS: Record<string, PixelSprite> = {
  jade_rabbit: {
    palette: { K: "#3b2a3a", W: "#fff6e6", P: "#e89aa8", G: "#7fd0ad" },
    frames: [[".K...K.", "KWK.KWK", "KWKKKWK", "KWWWWWK", "KWKWKWK", "KGWPWGK", ".KKKKK."]],
  },
  postmaster: {
    palette: { K: "#3b2a3a", B: "#5b78c4", W: "#fff6e6", Y: "#f5c542" },
    frames: [["K.....K", "KBKKKBK", "KBBBBBK", "KWKBKWK", "KBBYBBK", "KBBBBBK", ".KKKKK."]],
  },
  timekeeper: {
    palette: { K: "#3b2a3a", Y: "#d9a441", W: "#fff6e6" },
    frames: [[".KKKKK.", "KYWWWYK", "KWWKWWK", "KWWKKWK", "KWWWWWK", "KYWWWYK", ".KKKKK."]],
  },
  scholar: {
    palette: { K: "#3b2a3a", N: "#9a6a55", P: "#e89aa8", R: "#c8323a" },
    frames: [["KKKKKKK", ".KKKKKR", ".KNNNKR", "KNKNKNK", "KNNPNNK", "KNNNNNK", ".KKKKK."]],
  },
  stargazer: {
    palette: { K: "#3b2a3a", V: "#9a7ff0", W: "#fff6e6", Y: "#f5c542" },
    frames: [["Y.....Y", ".K...K.", ".KKKKK.", "KVVVVVK", "KVWVWVK", "KVVVVVK", ".KKKKK."]],
  },
};
