// Toolbar icons: 14x14 pixel maps in the game's palette (never scaled).

import type { PixelSprite } from "./art";

const PALETTE: Record<string, string> = {
  K: "#3b2a3a",
  W: "#fff6e6",
  w: "#e8d9bd",
  Y: "#f5c542",
  y: "#c99a3e",
  P: "#e89aa8",
  G: "#9aa0b0",
  g: "#4a3a5a",
  C: "#8fe0e0",
  N: "#a86f43",
  n: "#7a4a2a",
  R: "#d9503f",
  T: "#e8c89a",
  D: "#5b5470",
  S: "#c9c1d4",
  s: "#8a8298",
};

const ICONS: Record<string, string[]> = {
  moonpad: [
    "..KKKKKKKKKK..",
    "..KggggggggK..",
    "..KgCCCCCCgK..",
    "..KgCWWWCCgK..",
    "..KgCCCCCCgK..",
    "..KgCWWWWCgK..",
    "..KgCCCCCCgK..",
    "..KgCWWCCCgK..",
    "..KgCCCCCCgK..",
    "..KgCCCCCCgK..",
    "..KggggggggK..",
    "..KgggWWgggK..",
    "..KggggggggK..",
    "..KKKKKKKKKK..",
  ],
  shop: [
    ".KKKKKKKKKKKK.",
    ".KNNNNNNNNNNK.",
    ".KnnnnnnnnnnK.",
    ".KKKKKKKKKKKK.",
    ".KNNNNKKNNNNK.",
    ".KNNNKYYKNNNK.",
    ".KNNKYWYYKNNK.",
    ".KNNKYYYyKNNK.",
    ".KNNNKYyKNNNK.",
    ".KNNNNKKNNNNK.",
    ".KNNNNNNNNNNK.",
    ".KnnnnnnnnnnK.",
    ".KKKKKKKKKKKK.",
  ],
  quests: [
    ".KKKKKKKKKKK..",
    "KTWWWWWWWWWWK.",
    "KTKKKKKKKKKKK.",
    ".KWWWWWWWWWK..",
    ".KWWWWYWWWWK..",
    ".KWWWYYYWWWK..",
    ".KWYYYYYYYWK..",
    ".KWWYYYYYWWK..",
    ".KWWYYWYYWWK..",
    ".KWWWWWWWWWK..",
    ".KwwwwwwwwwK..",
    ".KKKKKKKKKKKK.",
    "..KWWWWWWWWWTK",
    "...KKKKKKKKKK.",
  ],
  help: [
    "....KKKKKK....",
    "...KWWWWWWK...",
    "..KWWKKKKWWK..",
    "..KWWK..KWWK..",
    "..KKKK..KWWK..",
    ".......KWWK...",
    "......KWWK....",
    "......KWWK....",
    "......KKKK....",
    "..............",
    "......KKKK....",
    "......KWWK....",
    "......KWWK....",
    "......KKKK....",
  ],
  call: [
    ".KKK..........",
    "KWWWK.........",
    "KWWWWK........",
    "KWWWWK........",
    ".KWWK.........",
    ".KWWK.........",
    "..KWWK........",
    "..KWWWK..KKK..",
    "...KWWWKKWWWK.",
    "....KWWWWWWWWK",
    ".....KWWWWWWWK",
    "......KKWWWWK.",
    "........KKKK..",
  ],
  edit: [
    "...........KK.",
    "..........KPPK",
    ".........KGPPK",
    "........KYGGK.",
    ".......KYYyK..",
    "......KYYyK...",
    ".....KYYyK....",
    "....KYYyK.....",
    "...KYYyK......",
    "..KYYyK.......",
    ".KTYyK........",
    ".KTTK.........",
    "KDKK..........",
    ".K............",
  ],
  talk: [
    "..............",
    "..KKKKKKKKKK..",
    ".KWWWWWWWWWWK.",
    "KWWWWWWWWWWWWK",
    "KWWKKWWKKWWKWK",
    "KWWKKWWKKWWKWK",
    "KWWWWWWWWWWWWK",
    ".KWWWWWWWWWWK.",
    "..KKWWKKKKKK..",
    "...KWK........",
    "...KK.........",
  ],
  letter: [
    "..............",
    "..............",
    "KKKKKKKKKKKKKK",
    "KWKWWWWWWWWKWK",
    "KWWKWWWWWWKWWK",
    "KWWWKWWWWKWWWK",
    "KWWWWKRRKWWWWK",
    "KWWWWWKKWWWWWK",
    "KWWWWWWWWWWWWK",
    "KwwwwwwwwwwwwK",
    "KKKKKKKKKKKKKK",
  ],
  build: [
    "..KKKKKKK.....",
    ".KGGGGGGGK....",
    "KGWWGGGGGGK...",
    "KGGGGGGGGGK...",
    ".KKKKNNKKKK...",
    "....KNNK......",
    "....KNNK......",
    "....KNNK......",
    "....KNNK......",
    "....KNNK......",
    "....KnnK......",
    "....KKKK......",
  ],
  grab: [
    "..............",
    ".....KKKK.....",
    "...KKSSSSKK...",
    "..KSSWSSSSSK..",
    ".KSSSSSSsSSSK.",
    ".KSsSSSSSSSSK.",
    ".KSSSSSsSSSsK.",
    ".KsSSSSSSSSSK.",
    "..KssSSSSSsK..",
    "...KKsssssKK..",
    ".....KKKKK....",
  ],
  sweep: [
    "...........KK.",
    "..........KNK.",
    ".........KNK..",
    "........KNK...",
    ".......KNK....",
    "......KNK.....",
    ".....KNK......",
    "...KKYYK......",
    "..KYYYYYK.....",
    ".KYYYYYYK.....",
    "KYYyYyYK......",
    "KYyYyYK.......",
    ".KKKKK........",
  ],
  light: [
    ".....KKKK.....",
    "....KYYYYK....",
    "...KYWWYYyK...",
    "...KYWYYYyK...",
    "...KYYYYYyK...",
    "...KYYYYYyK...",
    "....KYYYyK....",
    ".....KYyK.....",
    ".....KGGK.....",
    ".....KssK.....",
    ".....KGGK.....",
    ".....KKKK.....",
  ],
  pickaxe: [
    "..KKKKKKKK....",
    ".KGGGGGGGGK...",
    "KGWWGGGGGGGK..",
    "KGGKKKKKKGGK..",
    ".KK....KNNK...",
    ".......KNNK...",
    "......KNNK....",
    ".....KNNK.....",
    "....KNNK......",
    "...KNNK.......",
    "..KNnK........",
    ".KnnK.........",
    ".KKK..........",
  ],
  door: [
    "...KKKKKKKK...",
    "..KNNNNNNNNK..",
    "..KNnNNNNnNK..",
    "..KNnNNNNnNK..",
    "..KNnNNNNnNK..",
    "..KNNNNNNNNK..",
    "..KNnNNNNnNK..",
    "..KNnNNYNnNK..",
    "..KNnNNNNnNK..",
    "..KNnNNNNnNK..",
    "..KNNNNNNNNK..",
    "..KNNNNNNNNK..",
    ".KKKKKKKKKKKK.",
  ],
  music: [
    "......KKKKKK..",
    "......KWWWWK..",
    "......KWKKWK..",
    "......KWK.KK..",
    "......KWK.....",
    "......KWK.....",
    "......KWK.....",
    "..KKKKKWK.....",
    ".KWWWWWWK.....",
    "KWWWWWWWK.....",
    "KWWWWWWK......",
    ".KWWWWK.......",
    "..KKKK........",
  ],
  music_off: [
    "......KKKKKK..",
    "......KsssssK.",
    "......KsKKsK..",
    "......KsK.KK..",
    "KK....KsK...KK",
    ".KK...KsK..KK.",
    "..KK..KsK.KK..",
    "..KKKKKsKKK...",
    ".KssssssKK....",
    "KsssssKKKK....",
    "KssssKKsKK....",
    ".KKKKK...KK...",
    ".........KK...",
  ],
  sfx: [
    "..............",
    "......KK......",
    ".....KWK..K...",
    "....KWWK...K..",
    "KKKKWWWK.K..K.",
    "KWWWWWWK..K.K.",
    "KWWWWWWK..K.K.",
    "KWWWWWWK..K.K.",
    "KKKKWWWK.K..K.",
    "....KWWK...K..",
    ".....KWK..K...",
    "......KK......",
    "..............",
  ],
  sfx_off: [
    "..............",
    "......KK......",
    ".....KsK......",
    "....KssK......",
    "KKKKsssK......",
    "KssssssK.KK.KK",
    "KssssssK..KKK.",
    "KssssssK..KKK.",
    "KKKKsssK.KK.KK",
    "....KssK......",
    ".....KsK......",
    "......KK......",
    "..............",
  ],
  idle: [
    "..............",
    "..............",
    "..............",
    "..............",
    "..............",
    "..............",
    ".....KKKK.....",
    ".....KssK.....",
    ".....KssK.....",
    ".....KKKK.....",
  ],
  // Talk-dialog controls: push-to-talk mic (red while listening) and the voice toggle.
  mic: [
    "...KKK...",
    "..KWWWK..",
    "..KWsWK..",
    "..KWWWK..",
    "..KWsWK..",
    "..KWWWK..",
    "K.KKKKK.K",
    "K.......K",
    ".K.....K.",
    "..KKKKK..",
    "....K....",
    "..KKKKK..",
  ],
  mic_on: [
    "...KKK...",
    "..KRRRK..",
    "..KRWRK..",
    "..KRRRK..",
    "..KRWRK..",
    "..KRRRK..",
    "K.KKKKK.K",
    "K.......K",
    ".K.....K.",
    "..KKKKK..",
    "....K....",
    "..KKKKK..",
  ],
  sound_on: [
    "...W......",
    "..WW...W..",
    "WWWW.W..W.",
    "WWWW.W..W.",
    "WWWW.W..W.",
    "..WW...W..",
    "...W......",
  ],
  sound_off: [
    "...W......",
    "..WW.W...W",
    "WWWW..W.W.",
    "WWWW...W..",
    "WWWW..W.W.",
    "..WW.W...W",
    "...W......",
  ],
};

/** Every icon as a one-frame PixelSprite, keyed by name (texture `icon_<name>_0`). */
export const ICON_SPRITES: Record<string, PixelSprite> = Object.fromEntries(
  Object.entries(ICONS).map(([name, rows]) => [name, { palette: PALETTE, frames: [rows] }]),
);

/** The context action button's icon for each verb. */
export const VERB_ICON: Record<string, string> = {
  TALK: "icon_talk_0",
  "READ LETTER": "icon_letter_0",
  BUILD: "icon_build_0",
  POP: "clod_icon",
  GRAB: "icon_grab_0",
  SWEEP: "icon_sweep_0",
  CALL: "icon_call_0",
  CLEAR: "icon_pickaxe_0",
  ENTER: "icon_door_0",
  LEAVE: "icon_door_0",
  BOARD: "icon_quests_0",
  WATCH: "icon_talk_0",
  CHECK: "icon_quests_0",
  "TURN ON": "icon_light_0",
  "TURN OFF": "icon_light_0",
};

/** Tiny 7x7 villager heads, for the minimap and the roster (texture `vicon_<id>_0`). */
export const VILLAGER_ICONS: Record<string, PixelSprite> = {
  jade_rabbit: {
    palette: { K: "#3b2a3a", W: "#fff6e6", P: "#e89aa8", G: "#7fd0ad" },
    frames: [[".K...K.", "KWK.KWK", "KWKKKWK", "KWWWWWK", "KWKWKWK", "KGWPWGK", ".KKKKK."]],
  },
  postmaster: {
    palette: { K: "#3b2a3a", B: "#5b78c4", W: "#fff6e6", Y: "#f5c542" },
    frames: [["K.....K", "KBKKKBK", "KBBBBBK", "KWKBKWK", "KBBYBBK", "KBBBBBK", ".KKKKK."]],
  },
  timekeeper: {
    palette: { K: "#3b2a3a", Y: "#d9a441", W: "#fff6e6" },
    frames: [[".KKKKK.", "KYWWWYK", "KWWKWWK", "KWWKKWK", "KWWWWWK", "KYWWWYK", ".KKKKK."]],
  },
  scholar: {
    palette: { K: "#3b2a3a", N: "#9a6a55", P: "#e89aa8", R: "#c8323a" },
    frames: [["KKKKKKK", ".KKKKKR", ".KNNNKR", "KNKNKNK", "KNNPNNK", "KNNNNNK", ".KKKKK."]],
  },
  stargazer: {
    palette: { K: "#3b2a3a", V: "#9a7ff0", W: "#fff6e6", Y: "#f5c542" },
    frames: [["Y.....Y", ".K...K.", ".KKKKK.", "KVVVVVK", "KVWVWVK", "KVVVVVK", ".KKKKK."]],
  },
  manager: {
    palette: { K: "#3b2a3a", H: "#3b2a2a", S: "#f0c09a", B: "#3f4f8a" },
    frames: [[".KKKKK.", "KHHHHHK", "KHSSSHK", "KHKSKHK", "KHSSSHK", ".KBBBK.", ".KKKKK."]],
  },
};

/** Tiny 7x7 story items and jobs, for the town's requirement lists (texture `item_<id>_0`). */
export const ITEM_ICONS: Record<string, PixelSprite> = {
  charter: {
    palette: { K: "#3b2a3a", P: "#f4e2b8", D: "#c9a96a", R: "#c0392b" },
    frames: [[".KKKKK.", "KPPPPPK", ".KDDDPK", ".KPPPPK", ".KDDPPK", "KPPPPRK", ".KKKKK."]],
  },
  valve: {
    palette: { K: "#3b2a3a", R: "#d9503f", L: "#f08a7a", M: "#8e97a8" },
    frames: [["..KKK..", ".KRLRK.", "KRKMKRK", "KLMMMLK", "KRKMKRK", ".KRRRK.", "..KKK.."]],
  },
  lens: {
    palette: { K: "#3b2a3a", G: "#c99a3e", B: "#8fd0f0", W: "#e8f7ff" },
    frames: [["..KKK..", ".KGGGK.", "KGWBBGK", "KGBBBGK", "KGBBBGK", ".KGGGK.", "..KKK.."]],
  },
  bell: {
    palette: { K: "#3b2a3a", Y: "#f5c542", L: "#fff0a8", D: "#c99a3e" },
    frames: [["...K...", "..KYK..", ".KLYYK.", ".KYYYK.", "KYYYYDK", "KKKKKKK", "...K..."]],
  },
  search: {
    palette: { K: "#3b2a3a", B: "#8fd0f0", W: "#e8f7ff", H: "#8a5a3b" },
    frames: [[".KKK...", "KWBBK..", "KBBBK..", "KBBBK..", ".KKKHK.", "....KHK", ".....KK"]],
  },
  job: {
    palette: { K: "#3b2a3a", Y: "#f5c542", L: "#fff0a8" },
    frames: [["...K...", "..KYK..", "KKKLKKK", "KYYYYYK", ".KYYYK.", ".KYKYK.", "KK...KK"]],
  },
  room: {
    palette: { K: "#3b2a3a", R: "#e0708a", W: "#fff2d6", D: "#8a4b1f" },
    frames: [["...K...", "..KRK..", ".KRRRK.", "KRRRRRK", ".KWWWK.", ".KWDWK.", ".KKKKK."]],
  },
};

/** Tiny 7x7 materials for the HUD and pickups (texture `mat_<material>_0`). */
export const MATERIAL_ICONS: Record<string, PixelSprite> = {
  moonstone: {
    palette: { K: "#3b2a3a", G: "#9a93a8", L: "#c8c1d6", D: "#6f6880" },
    frames: [[".......", "..KKK..", ".KLLGK.", "KLGGGDK", "KGGGDDK", ".KDDDK.", "..KKK.."]],
  },
  stardust: {
    palette: { K: "#3b2a3a", Y: "#f5c542", W: "#fff6c8" },
    frames: [["...Y...", "...W...", "YWWWWWY", "...W...", ".Y.Y.Y.", "Y.....Y", "...Y..."]],
  },
  ore: {
    palette: { K: "#3b2a3a", O: "#ffb347", Y: "#ffe7a0", D: "#6f6886" },
    frames: [[".......", "..KKK..", ".KOYOK.", "KDOYOOK", "KDDOODK", ".KDDDK.", "..KKK.."]],
  },
  ice: {
    palette: { K: "#2f4f6f", I: "#8fd0f0", W: "#e8f7ff", B: "#5aa0c8" },
    frames: [["...K...", "..KWK..", ".KWIIK.", ".KWIBK.", "KWIIIBK", "KIIBBBK", ".KKKKK."]],
  },
  scrap: {
    palette: { K: "#3b2a3a", M: "#8e97a8", L: "#c3cad6", R: "#a0583a" },
    frames: [[".......", ".KKKK..", ".KLMMK.", "KKKMRRK", "KLMMRRK", "KMMMMK.", ".KKKK.."]],
  },
  helium: {
    palette: { K: "#2f5f58", G: "#a8e8d0", W: "#ffffff", L: "#e4fff4" },
    frames: [["...W...", ".......", "..KKK..", ".KLGGK.", "KLGGGGK", "KGGGGGK", ".KKKKK."]],
  },
  shard: {
    palette: { K: "#1f4a5a", C: "#8ff0f0", W: "#e8fbff", B: "#4fb8c8" },
    frames: [["...K...", "..KWK..", "..KCK..", ".KWCBK.", ".KCCBK.", "..KBK..", "...K..."]],
  },
};
